export enum DialogNavigationEnum {
    ADD_CLUSTER_DIALOG_VIEW = 'ADD_CLUSTER_DIALOG_VIEW',
    ADD_MONEY_DIALOG_VIEW = 'ADD_MONEY_DIALOG_VIEW',
    MONEY_PREVIEW_DIALOG_VIEW = 'MONEY_PREVIEW_DIALOG_VIEW',

}